server:
  port: 18088

management:
  endpoints:
    web:
      exposure:
        include: '*'

config-map-class-path: classpath:config-map.yaml
file-path: D:\git\mqtt-auth-demo\src\main\resources\config-map.yaml
config-map-file-path: file:${file-path}