server:
  port: 18088

config-map:
  scopes:
    - mqtt
  topics:
    - topic: "/services/{serviceName}/devices/getDeviceLogs/#"
      client:
        - service
      actions:
        - sub
    - topic: "/users/+/{serviceName}/"
      client:
        - service
      actions:
        - pub
        - sub
    - topic: "/services/{serviceName}/vehicles/#"
      client:
        - service
      actions:
        - pub