config-map:
  scopes:
    - mqtt
  topics:
    - topic: "/users/{userId}/vehicles/{pvin}/#"
      client:
        - device
      actions:
        - sub
      permissions:
        - vehicle:view
    - topic: "/users/{userId}/customers/#"
      client:
        - user
      actions:
        - pub